apiVersion: v1
kind: Pod
metadata:
  name: ffmpeg
  labels:
    app: ffmpeg
spec:
  containers:
  - image: robinhoodis/ffmpeg:0.0.6
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: Always
    name: ffmpeg
  restartPolicy: Always
